### ISSUE TITLE
managedDevices is missing under /beta/deviceManagement/

### ISSUE THREAD

**Issue by jhochwald** [estruyf/vscode-msgraph-autocomplete#2]
Just started to test the extension, found that the **managedDevices** completion isn't there under the following URL:
_https://graph.microsoft.com/beta/deviceManagement/managedDevices/_

**Comment by estruyf** [comment]
Thanks for creating the issue @jhochwald! It can be that for some of the beta endpoints all API paths are not yet available. Now I have checked for the one you specified and this requires you to add the managed device ID. I will add support for this, that it is more clear.

**Comment by estruyf** [comment]
@jhochwald this is now supported in `0.0.6`.

![Screenshot 2021-03-25 at 13 26 55](https://user-images.githubusercontent.com/2900833/112472821-dd60ea80-8d6d-11eb-8cff-63c306318883.png)

![Screenshot 2021-03-25 at 13 27 07](https://user-images.githubusercontent.com/2900833/112472830-df2aae00-8d6d-11eb-880c-1c0efdabdce9.png)

**Comment by jhochwald** [comment]
Awesome! It works fine.

Hint: Parameters? Is it an option?
Like these: _https://graph.microsoft.com/beta/deviceManagement/managedDevices/<GUID>?$select=iccid,phoneNumber_

**Comment by estruyf** [comment]
@jhochwald sorry, missed the question as you closed the issue. This is not an option. It seems that not all APIs have this information available. So if it is not shown, it is simply not returned.
